import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "sonner";
import Providers from "@/Providers";
import Footer from "@/components/layout/Footer";


const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <Navbar />

          <main className="min-h-[85vh]">{children}</main>


          <Footer />
        </Providers>

          <Toaster />

      </body>
    </html>
  );
}
